builds:
  - binary: oscalkit
    main: ./cli/main.go
    ldflags: -s -w -X github.com/opencontrol/oscalkit/cli/version.Version={{.Version}} -X github.com/opencontrol/oscalkit/cli/version.Commit={{.Commit}} -X github.com/opencontrol/oscalkit/cli/version.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

nfpm:
  homepage: https://github.com/opencontrol/oscalkit
  license: CC0 1.0
  dependencies:
    - libxml2-utils
  formats:
    - deb
    - rpm

dockers:
  - image: opencontrolorg/oscalkit
    dockerfile: Dockerfile.release
    tag_templates:
      - "{{ .Version }}"
      - latest

brew:
  name: oscalkit
  github:
    owner: opencontrol
    name: homebrew-oscalkit
  commit_author:
    name: OpenControl
    email: dev@open-control.org
  homepage: https://github.com/opencontrol/oscalkit
  dependencies:
    - libxml2