baseURL = "https://opencontrol.github.io/oscalkit/"
languageCode = "en-us"
title = "oscalkit"
theme = "oscalkit"
description = "oscalkit is a CLI and Go SDK for OSCAL"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "oscalkit" # add your company name
  github = "oscalkit" # add your github profile name
  twitter = "" # add your twitter profile
  email = ""

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
# [[menu.main]]
#     name = "Blog"
#     weight = -100
#     url = "/blog/"
# [[menu.main]]
#     name = "Faq"
#     weight = -100
#     url = "/faq/"